#!/bin/bash

STATE_FILE="/home/kalex/.xmonad/scripts/microphone_state"

if [ "$1" = "0" ]; then
    echo -n "1" > $STATE_FILE
	pactl set-source-mute 1 0
else
    echo -n "0" > $STATE_FILE
	pactl set-source-mute 1 1
fi
