#!/bin/sh

INTERFACE="wlp3s0"

iwconfig "$INTERFACE" 2>&1 | grep -q no\ wireless\ extensions\. && {
  echo "<fn=1> </fn>"
  exit 0
}

essid=`iwconfig "$INTERFACE" | awk -F '"' '/ESSID/ {print $2}'`
stngth=`iwconfig "$INTERFACE" | awk -F '=' '/Quality/ {print $2}' | cut -d '/' -f 1`

echo "<fn=1> </fn> $stngth"
exit 0

bars=`expr $stngth / 10`
case $bars in
  0)  bar='[----------]' ;;
  1)  bar='[/---------]' ;;
  2)  bar='[//--------]' ;;
  3)  bar='[///-------]' ;;
  4)  bar='[////------]' ;;
  5)  bar='[/////-----]' ;;
  6)  bar='[//////----]' ;;
  7)  bar='[///////---]' ;;
  8)  bar='[////////--]' ;;
  9)  bar='[/////////-]' ;;
  10) bar='[//////////]' ;;
  *)  bar='[----!!----]' ;;
esac

echo $bar

exit 0
