resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/7.yaml

system-ghc: false

# User packages to be built.
packages:
  # - xmobar-git
  - xmonad
  - xmonad-contrib
  - xmonad-dbus

extra-deps:
  - netlink-1.1.1.0

flags:
  # xmobar:
  #   all_extensions: true
