#!/bin/bash
num=$((1 + RANDOM % 500))

quote=$(jq --arg num "$num" ".[$num]" < /tmp/xmonad/quotes/quotes.json)
echo "$quote" | jq -r ".text" > /tmp/xmonad/quotes/quote
echo "$quote" | jq -r ".author" > /tmp/xmonad/quotes/author

quote=$(cat /tmp/xmonad/quotes/quote)
qc=$(wc -c < /tmp/xmonad/quotes/quote)
rm -f /tmp/xmonad/quotes/quote
rm -f /tmp/xmonad/quotes/quote-tail
if [ "$qc" -le 58 ]; then
  echo "$quote" > /tmp/xmonad/quotes/quote
  echo "" > /tmp/xmonad/quotes/quote-tail
else
  printf '%s\n' "${quote:0:${#quote}/2}" > /tmp/xmonad/quotes/quote
  printf '%s\n' "${quote:${#quote}/2}" > /tmp/xmonad/quotes/quote-tail
fi
