#!/bin/sh
#
pkgUpdates() {
	updates=$(tail /tmp/checkupdates -n1)

	if [ "$updates" = "" ]; then
		echo "Up to date!"
	else
		echo "󱍸  $updates updates"
	fi
}

battery() {
	cat /sys/class/power_supply/BAT0/capacity
}

cpu() {
	load=$(grep -o "^[^ ]*" /proc/loadavg)
	procs=$(nproc)
	awk "BEGIN {print ($load/$procs * 100/5)}"
}

disk() {
	df --output=pcent /home | tail -n 1 | tr -d '[:space:]|%'
}

ram() {
	printf "%.0f\n" "$(free -m | grep Mem | awk '{print ($3/$2)*100}')"
}

backlight() {
	brightnessctl -m | cut -d',' -f4 | tr -d '%'
}

wifi() {
	case "$(cat /sys/class/net/wl*/operstate 2>/dev/null)" in
	up) printf "󰤨" ;;
	down) printf "󰤭" ;;
	esac
}

"$@"
