#!/bin/bash
vpn_name="HomeVPN"
state=$(ifconfig | grep "$vpn_name")

if [ "$state" != "" ]; then
	nmcli con down HomeVPN
	echo "#D35D6E" >/tmp/xmonad/vpnstat-hex
else
	nmcli con up HomeVPN
	echo "#61afef" >/tmp/xmonad/vpnstat-hex
fi
