#!/bin/zsh

if [ "$(pgrep -cx polybar)" -gt 0 ]; then
    echo "The panel is running. Stopping it"
    pkill -nx "polybar"
    sleep 1.5
    while [ "$(pgrep -cx polybar)" -gt 0 ]; do
        pkill -nx -9 "polybar"
    done
fi

export MONITOR="$(xrandr -q | rg "connected primary" | cut -d' ' -f1)"
polybar --config=/home/kalex/.config/polybar/config.ini main &
wait
