#!/bin/zsh

# 
if [ "$(pgrep -cx polybar)" -gt 0 ]; then
    echo "The panel is running. Stopping it"
    pkill -nx "polybar"
    sleep 1.5
    while [ "$(pgrep -cx polybar)" -gt 0 ]; do
        pkill -nx -9 "polybar"
    done
fi

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --config=/home/kalex/.config/polybar/config.ini main & >> /tmp/polybar.log 2>&1
  done
else
  polybar --reload example &
fi
wait
